services:
  - type: web
    name: blekon-api
    runtime: docker
    plan: free
    autoDeploy: true
    branch: master
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "false"
